name: Golang Formatter

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Golang Formatter
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 0
    - name: Golang Formatter
      uses: borkaz/gofmt-github-action@main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
